### ISSUE TITLE
Typo in kernel internals

### ISSUE THREAD

**Issue by AcK77** [marcussacana/OrbisGL#6]
While looking at the code, I found a little typo there:

```c#
[DllImport("libSceRtc.srpx")]
```

Should be 

```c#
[DllImport("libSceRtc.sprx")]
```

at https://github.com/marcussacana/OrbisGL/blob/master/OrbisGL/Internals/Kernel.cs#L115

**Comment by marcussacana** [comment]
True, I will fix right now.

**Comment by marcussacana** [comment]
done.
